import "@/styles/style.scss"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header id="header">
      <div className="hd-content">
        <div className="hd-logo">
          <a href="/" className="logo-icon"></a>
          <a href="/" className="logo-title">ポートフォリオ</a>
        </div>
        <nav className="hd-nav-sub">
          <ul>
            <li className="active-hd-nav">
              <a href="/#weare">What I can do</a>
            </li>
            <li>
              <a href="/#myskill">Skills</a>
            </li>
            <li>
              <a href="/#myworks">Works</a>
            </li>
          </ul>
        </nav>
      </div>
    </header>
  );
}

function Footer() {
  return (
    <footer>
      <div className="put-center">
        <p>&copy; 2023 Hosoda Yoshiki. All Rights Reserved.</p>
      </div>
    </footer>
  );
}

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body>
        <Header />
        {children}
        <div id="floating-icons">
          <a
            href="#header"
            className="page-up-arrow"
          >
            <i className="fa-solid fa-arrow-up fa-3x"></i>
          </a>
        </div>
        <Footer />
      </body>
    </html>
  );
}
